export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGIN_LOGOUT";

export const SAVE_IMAGES = "SAVE_IMAGES";
export const SAVE_LIST_IMAGES = "SAVE_LIST_IMAGES";
export const UPDATE_LIST_IMAGE = "UPDATE_LIST_IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";

export const SAVE_ORDER = "SAVE_ORDERS";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";

export const CREATE_DISCOUNT = "CREATE_DISCOUNT";
